import { lazy } from 'react'

export const LoginPage = lazy(() => import('../features/auth/LoginPage').then((module) => ({ default: module.LoginPage })))
export const DashboardPage = lazy(() => import('../features/dashboard/DashboardPage').then((module) => ({ default: module.DashboardPage })))
export const FallbackModulePage = lazy(() => import('../features/fallback/FallbackModulePage').then((module) => ({ default: module.FallbackModulePage })))
export const TableAdminPage = lazy(() => import('../features/field-admin/TableAdminPage').then((module) => ({ default: module.TableAdminPage })))
export const FieldEditorRoute = lazy(() => import('../features/field-admin/FieldEditorPage').then((module) => ({ default: module.FieldEditorRoute })))
export const FieldAuditPage = lazy(() => import('../features/admin/FieldAuditPage').then((module) => ({ default: module.FieldAuditPage })))
export const LogAdminPage = lazy(() => import('../features/admin/LogAdminPage').then((module) => ({ default: module.LogAdminPage })))
export const DepotStockPolicyPage = lazy(() => import('../features/admin/DepotStockPolicyPage').then((module) => ({ default: module.DepotStockPolicyPage })))
export const UserAdminPage = lazy(() => import('../features/user-admin/UserAdminPage').then((module) => ({ default: module.UserAdminPage })))
export const UserRightsPage = lazy(() => import('../features/user-admin/UserAdminPages').then((module) => ({ default: module.UserRightsPage })))

export const UserButtonRightsPage = lazy(() => import('../features/user-admin/UserAdminPages').then((module) => ({ default: module.UserButtonRightsPage })))
export const UserGroupAdminPage = lazy(() => import('../features/rights-admin/UserGroupAdminPage').then((module) => ({ default: module.UserGroupAdminPage })))
export const GroupRightsPage = lazy(() => import('../features/rights-admin/GroupAdminPages').then((module) => ({ default: module.GroupRightsPage })))

export const GroupButtonRightsPage = lazy(() => import('../features/rights-admin/GroupAdminPages').then((module) => ({ default: module.GroupButtonRightsPage })))
export const GroupMembersPage = lazy(() => import('../features/rights-admin/GroupAdminPages').then((module) => ({ default: module.GroupMembersPage })))
export const MenuAdminPage = lazy(() => import('../features/menu-admin/MenuAdminPage').then((module) => ({ default: module.MenuAdminPage })))
export const ProfilePage = lazy(() => import('../features/settings/ProfilePage').then((module) => ({ default: module.ProfilePage })))
export const SystemSettingsPage = lazy(() => import('../features/settings/SystemSettingsPage').then((module) => ({ default: module.SystemSettingsPage })))
export const BomExpandPage = lazy(() => import('../features/bom/BomExpandPage').then((module) => ({ default: module.BomExpandPage })))
export const CarSummaryPage = lazy(() => import('../features/reports/CarSummaryPage').then((module) => ({ default: module.CarSummaryPage })))
export const DetailQueryPage = lazy(() => import('../features/reports/DetailQueryPage').then((module) => ({ default: module.DetailQueryPage })))
export const JobPage = lazy(() => import('../features/jobs/JobPage').then((module) => ({ default: module.JobPage })))
export const SearchCenterPage = lazy(() => import('../features/search-center/SearchCenterPage').then((module) => ({ default: module.SearchCenterPage })))
export const ImportPage = lazy(() => import('../features/import/ImportPage').then((module) => ({ default: module.ImportPage })))
export const PrintViewPage = lazy(() => import('../features/print/PrintViewPage').then((module) => ({ default: module.PrintViewPage })))
export const MyTasksPage = lazy(() => import('../features/workflow/MyTasksPage').then((module) => ({ default: module.MyTasksPage })))
export const FlowDesignPage = lazy(() => import('../features/workflow/FlowDesignPage').then((module) => ({ default: module.FlowDesignPage })))
export const FlowMonitorPage = lazy(() => import('../features/workflow/FlowMonitorPage').then((module) => ({ default: module.FlowMonitorPage })))
export const ReportCenterPage = lazy(() => import('../features/reports/ReportCenterPage').then((module) => ({ default: module.ReportCenterPage })))
export const ReportInboxPage = lazy(() => import('../features/reports/ReportInboxPage').then((module) => ({ default: module.ReportInboxPage })))
export const LayoutDesignerPage = lazy(() => import('../features/layout-designer/LayoutDesignerPage').then((module) => ({ default: module.LayoutDesignerPage })))
