import { lazy } from 'react'

export const LoginPage = lazy(() => import('../features/auth/LoginPage').then((module) => ({ default: module.LoginPage })))
export const DashboardPage = lazy(() => import('../features/dashboard/DashboardPage').then((module) => ({ default: module.DashboardPage })))
export const LegacyModulePage = lazy(() => import('../features/legacy/LegacyModulePage').then((module) => ({ default: module.LegacyModulePage })))
export const PurchaseOrdersPage = lazy(() => import('../features/procurement/pages/PurchaseOrdersPage').then((module) => ({ default: module.PurchaseOrdersPage })))
export const TableAdminPage = lazy(() => import('../features/field-admin/TableAdminPage').then((module) => ({ default: module.TableAdminPage })))
export const TableDataPage = lazy(() => import('../features/admin/TableDataPage').then((module) => ({ default: module.TableDataPage })))
export const FieldAuditPage = lazy(() => import('../features/admin/FieldAuditPage').then((module) => ({ default: module.FieldAuditPage })))
export const UserAdminPage = lazy(() => import('../features/user-admin/UserAdminPage').then((module) => ({ default: module.UserAdminPage })))
export const ProfilePage = lazy(() => import('../features/settings/ProfilePage').then((module) => ({ default: module.ProfilePage })))
export const SystemSettingsPage = lazy(() => import('../features/settings/SystemSettingsPage').then((module) => ({ default: module.SystemSettingsPage })))
export const BomExpandPage = lazy(() => import('../features/bom/BomExpandPage').then((module) => ({ default: module.BomExpandPage })))
export const JobPage = lazy(() => import('../features/jobs/JobPage').then((module) => ({ default: module.JobPage })))
export const ReportViewerPage = lazy(() => import('../features/reports/ReportViewerPage').then((module) => ({ default: module.ReportViewerPage })))
export const SearchCenterPage = lazy(() => import('../features/search-center/SearchCenterPage').then((module) => ({ default: module.SearchCenterPage })))
export const ImportPage = lazy(() => import('../features/import/ImportPage').then((module) => ({ default: module.ImportPage })))
export const PrintViewPage = lazy(() => import('../features/print/PrintViewPage').then((module) => ({ default: module.PrintViewPage })))
export const MyTasksPage = lazy(() => import('../features/workflow/MyTasksPage').then((module) => ({ default: module.MyTasksPage })))
