import { createBrowserRouter, Navigate } from 'react-router-dom'
import { AppShell } from '../components/layout/AppShell'
import { RequireAuth, RequirePermission } from '../features/auth/RouteGuards'
import { ErrorPage } from './ErrorPage'
import {
  DashboardPage,
  DetailQueryPage,
  FieldAuditPage,
  FieldEditorRoute,
  BomExpandPage,
  CarSummaryPage,
  ImportPage,
  JobPage,
  LegacyModulePage,
  LoginPage,
  MyTasksPage,
  FlowDesignPage,
  FlowMonitorPage,
  PrintViewPage,
  ProfilePage,
  SearchCenterPage,
  SystemSettingsPage,
  TableAdminPage,
  UserAdminPage,
  UserRightsPage,
  UserReportRightsPage,
  UserGroupAdminPage,
  GroupRightsPage,
  GroupReportRightsPage,
  GroupMembersPage,
  MenuAdminPage,
  ReportCenterPage,
} from './lazyRoutes'
import { FieldAdminRoute, ForbiddenPage, FormEditorRoute, PrintSetupRoute, ReportAdminRoute, ReportViewerRoute, WorkbenchRoute } from './routeElements'
import { withSuspense } from './suspense'

export const router = createBrowserRouter([
  { path: '/login', element: withSuspense(<LoginPage />) },
  { path: '/forbidden', element: <ForbiddenPage /> },
  {
    element: <RequireAuth />,
    children: [{
      path: '/', element: <AppShell />, errorElement: <ErrorPage />, children: [
        { index: true, element: <Navigate to="/dashboard" replace /> },
        { path: 'dashboard', element: withSuspense(<DashboardPage />) },
        { path: 'legacy/modules/:moduleId', element: withSuspense(<LegacyModulePage />) },
        { element: <RequirePermission permission="legacy-module.2302.read" />, children: [
          { path: 'admin/tables', element: withSuspense(<TableAdminPage />) },
          { path: 'admin/tables/:tableId/fields', element: withSuspense(<FieldAdminRoute />) },
          { path: 'admin/fields/:tableId/:fieldId', element: withSuspense(<FieldEditorRoute />) },
        ] },
        { element: <RequirePermission permission="legacy-module.2301.read" />, children: [{ path: 'admin/menus', element: withSuspense(<MenuAdminPage />) }] },
        { element: <RequirePermission permission="legacy-module.2305.read" />, children: [
          { path: 'admin/groups', element: withSuspense(<UserGroupAdminPage />) },
          { path: 'admin/groups/:groupId/rights', element: withSuspense(<GroupRightsPage />) },
          { path: 'admin/groups/:groupId/report-rights', element: withSuspense(<GroupReportRightsPage />) },
          { path: 'admin/groups/:groupId/members', element: withSuspense(<GroupMembersPage />) },
        ] },
        { element: <RequirePermission permission="legacy-module.2303.read" />, children: [{ path: 'admin/field-audit', element: withSuspense(<FieldAuditPage />) }] },
        { element: <RequirePermission permission="legacy-module.2306.read" />, children: [
          { path: 'admin/users', element: withSuspense(<UserAdminPage />) },
          { path: 'admin/users/:userId/rights', element: withSuspense(<UserRightsPage />) },
          { path: 'admin/users/:userId/report-rights', element: withSuspense(<UserReportRightsPage />) },
        ] },
        { path: 'admin/report-setup', element: withSuspense(<ReportAdminRoute />) },
        { path: 'admin/print-setup/:tab?', element: withSuspense(<PrintSetupRoute />) },
        { path: 'workbench/:moduleId', element: withSuspense(<WorkbenchRoute />) },
        { path: 'workbench/:moduleId/new', element: withSuspense(<FormEditorRoute />) },
        { path: 'workbench/:moduleId/edit/*', element: withSuspense(<FormEditorRoute />) },
        { path: 'workbench/:moduleId/view/*', element: withSuspense(<FormEditorRoute />) },
        { path: 'workbench/:moduleId/copy', element: withSuspense(<FormEditorRoute />) },
        { path: 'reports/:moduleId', element: withSuspense(<ReportViewerRoute />) },
        { path: 'report-center', element: withSuspense(<ReportCenterPage />) },
        { path: 'search-center/:moduleId?', element: withSuspense(<SearchCenterPage />) },
        { path: 'import', element: withSuspense(<ImportPage />) },
        { path: 'print/:moduleId', element: withSuspense(<PrintViewPage />) },
        { path: 'bom-expand', element: withSuspense(<BomExpandPage />) },
        { element: <RequirePermission permission="legacy-module.199901.read" />, children: [{ path: 'car-summary', element: withSuspense(<CarSummaryPage />) }] },
        { path: 'detail-query/:moduleId', element: withSuspense(<DetailQueryPage />) },
        { element: <RequirePermission permission="legacy-module.2102.read" />, children: [{ path: 'my-tasks', element: withSuspense(<MyTasksPage />) }] },
        { element: <RequirePermission permission="legacy-module.2101.read" />, children: [{ path: 'workflow/design', element: withSuspense(<FlowDesignPage />) }] },
        { element: <RequirePermission permission="legacy-module.2103.read" />, children: [{ path: 'workflow/monitor', element: withSuspense(<FlowMonitorPage />) }] },
        { path: 'jobs', element: withSuspense(<JobPage />) },
        { path: 'legacy/modules/:moduleId', element: withSuspense(<LegacyModulePage />) },
        { path: 'settings/profile', element: withSuspense(<ProfilePage />) },
        { path: 'settings/:table', element: withSuspense(<SystemSettingsPage />) },
      ],
    }],
  },
])
