import {
  IconBarcode,
  IconBallpen,
  IconBasket,
  IconBell,
  IconBook,
  IconBookmark,
  IconBox,
  IconBriefcase,
  IconBuilding,
  IconBuildingFactory,
  IconBuildingBank,
  IconCalculator,
  IconCalendar,
  IconCalendarEvent,
  IconCamera,
  IconCash,
  IconCashBanknote,
  IconCertificate,
  IconCar,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconChecks,
  IconClipboardCheck,
  IconClipboardList,
  IconClock,
  IconCoins,
  IconCreditCard,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconCurrencyYen,
  IconDashboard,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconFile,
  IconFileSpreadsheet,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFolder,
  IconGauge,
  IconGavel,
  IconGift,
  IconGitBranch,
  IconGlobe,
  IconHandStop,
  IconHash,
  IconHeart,
  IconId,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLayout,
  IconLink,
  IconList,
  IconListCheck,
  IconLock,
  IconLockOpen,
  IconMap,
  IconMapPin,
  IconMessages,
  IconMoneybag,
  IconNews,
  IconNotebook,
  IconPackage,
  IconPalette,
  IconPercentage,
  IconPhoto,
  IconPill,
  IconPlug,
  IconPrinter,
  IconReportMoney,
  IconReport,
  IconRobot,
  IconRocket,
  IconScale,
  IconScan,
  IconShare,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconShoppingCart,
  IconSettings,
  IconStack,
  IconStar,
  IconTable,
  IconTag,
  IconTarget,
  IconTestPipe,
  IconTimeline,
  IconTool,
  IconTools,
  IconTrendingDown,
  IconTrendingUp,
  IconTruck,
  IconTruckDelivery,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserPlus,
  IconUsers,
  IconVaccine,
  IconVideo,
  IconWallet,
  IconWorld,
  IconZoomScan,
} from '@tabler/icons-react'

/** 侧栏/菜单管理共用：图标名 → Tabler 图标组件（与 /api/app/bootstrap 返回的 icon 名一致）。 */
export const navigationIcons: Record<string, typeof IconFolder> = {
  dashboard: IconDashboard,
  procurement: IconShoppingCart,
  sales: IconReportMoney,
  inventory: IconTruckDelivery,
  settings: IconSettings,
  folder: IconFolder,
  production: IconBuildingFactory,
  hr: IconUsers,
  finance: IconCoins,
  quality: IconClipboardCheck,
  report: IconChartBar,
  base: IconDatabase,
  equipment: IconTools,
  customer: IconBriefcase,
  supplier: IconTruck,
  document: IconFileText,
  product: IconPackage,
  vehicle: IconCar,
  barcode: IconBarcode,
  workflow: IconGitBranch,
  sample: IconPalette,
  query: IconZoomScan,
  outsource: IconTruck,
  customs: IconWorld,
  reportFile: IconReport,
  chartLine: IconChartLine,
  chartPie: IconChartPie,
  calendar: IconCalendar,
  calendarEvent: IconCalendarEvent,
  clock: IconClock,
  desktop: IconDeviceDesktop,
  mobile: IconDeviceMobile,
  printer: IconPrinter,
  building: IconBuilding,
  bank: IconBuildingBank,
  wallet: IconWallet,
  cash: IconCash,
  banknote: IconCashBanknote,
  creditCard: IconCreditCard,
  yen: IconCurrencyYen,
  dollar: IconCurrencyDollar,
  euro: IconCurrencyEuro,
  percent: IconPercentage,
  pen: IconBallpen,
  checklist: IconClipboardList,
  stack: IconStack,
  box: IconBox,
  basket: IconBasket,
  user: IconUser,
  userPlus: IconUserPlus,
  userCircle: IconUserCircle,
  id: IconId,
  key: IconKey,
  lock: IconLock,
  lockOpen: IconLockOpen,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  shieldLock: IconShieldLock,
  bell: IconBell,
  book: IconBook,
  bookmark: IconBookmark,
  calculator: IconCalculator,
  camera: IconCamera,
  certificate: IconCertificate,
  checks: IconChecks,
  file: IconFile,
  spreadsheet: IconFileSpreadsheet,
  filter: IconFilter,
  flag: IconFlag,
  gauge: IconGauge,
  gift: IconGift,
  globe: IconGlobe,
  hash: IconHash,
  heart: IconHeart,
  inbox: IconInbox,
  info: IconInfoCircle,
  layout: IconLayout,
  link: IconLink,
  list: IconList,
  listCheck: IconListCheck,
  map: IconMap,
  mapPin: IconMapPin,
  messages: IconMessages,
  moneybag: IconMoneybag,
  news: IconNews,
  notebook: IconNotebook,
  photo: IconPhoto,
  pill: IconPill,
  plug: IconPlug,
  robot: IconRobot,
  rocket: IconRocket,
  scale: IconScale,
  scan: IconScan,
  share: IconShare,
  star: IconStar,
  table: IconTable,
  tag: IconTag,
  target: IconTarget,
  testPipe: IconTestPipe,
  timeline: IconTimeline,
  tool: IconTool,
  trendUp: IconTrendingUp,
  trendDown: IconTrendingDown,
  upload: IconUpload,
  video: IconVideo,
  vaccine: IconVaccine,
  gavel: IconGavel,
  handStop: IconHandStop,
}
