import {
  IconBarcode,
  IconBallpen,
  IconBasket,
  IconBell,
  IconBook,
  IconBookmark,
  IconBox,
  IconBriefcase,
  IconBuilding,
  IconBuildingFactory,
  IconBuildingBank,
  IconCalculator,
  IconCalendar,
  IconCalendarEvent,
  IconCamera,
  IconCash,
  IconCashBanknote,
  IconCertificate,
  IconCar,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconChecks,
  IconClipboardCheck,
  IconClipboardList,
  IconClock,
  IconCoins,
  IconCreditCard,
  IconCurrencyDollar,
  IconCurrencyEuro,
  IconCurrencyYen,
  IconDashboard,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconFile,
  IconFileSpreadsheet,
  IconFileText,
  IconFilter,
  IconFlag,
  IconFolder,
  IconGauge,
  IconGavel,
  IconGift,
  IconGitBranch,
  IconGlobe,
  IconHandStop,
  IconHash,
  IconHeart,
  IconId,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconLayout,
  IconLink,
  IconList,
  IconListCheck,
  IconLock,
  IconLockOpen,
  IconMap,
  IconMapPin,
  IconMessages,
  IconMoneybag,
  IconNews,
  IconNotebook,
  IconPackage,
  IconPalette,
  IconPercentage,
  IconPhoto,
  IconPill,
  IconPlug,
  IconPrinter,
  IconReportMoney,
  IconReport,
  IconRobot,
  IconRocket,
  IconScale,
  IconScan,
  IconShare,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconShoppingCart,
  IconSettings,
  IconStack,
  IconStar,
  IconTable,
  IconTag,
  IconTarget,
  IconTestPipe,
  IconTimeline,
  IconTool,
  IconTools,
  IconTrendingDown,
  IconTrendingUp,
  IconTruck,
  IconTruckDelivery,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserPlus,
  IconUsers,
  IconVaccine,
  IconVideo,
  IconWallet,
  IconWorld,
  IconZoomScan,
} from '@tabler/icons-react'

/** 侧栏/菜单管理共用：图标名 → Tabler 图标组件（与 /api/app/bootstrap 返回的 icon 名一致）。 */
export const navigationIcons: Record<string, typeof IconFolder> = {
  dashboard: IconDashboard,
  procurement: IconShoppingCart,
  sales: IconReportMoney,
  inventory: IconTruckDelivery,
  settings: IconSettings,
  folder: IconFolder,
  production: IconBuildingFactory,
  hr: IconUsers,
  finance: IconCoins,
  quality: IconClipboardCheck,
  report: IconChartBar,
  base: IconDatabase,
  equipment: IconTools,
  customer: IconBriefcase,
  supplier: IconTruck,
  document: IconFileText,
  product: IconPackage,
  vehicle: IconCar,
  barcode: IconBarcode,
  workflow: IconGitBranch,
  sample: IconPalette,
  query: IconZoomScan,
  outsource: IconTruck,
  customs: IconWorld,
  reportFile: IconReport,
  chartLine: IconChartLine,
  chartPie: IconChartPie,
  calendar: IconCalendar,
  calendarEvent: IconCalendarEvent,
  clock: IconClock,
  desktop: IconDeviceDesktop,
  mobile: IconDeviceMobile,
  printer: IconPrinter,
  building: IconBuilding,
  bank: IconBuildingBank,
  wallet: IconWallet,
  cash: IconCash,
  banknote: IconCashBanknote,
  creditCard: IconCreditCard,
  yen: IconCurrencyYen,
  dollar: IconCurrencyDollar,
  euro: IconCurrencyEuro,
  percent: IconPercentage,
  pen: IconBallpen,
  checklist: IconClipboardList,
  stack: IconStack,
  box: IconBox,
  basket: IconBasket,
  user: IconUser,
  userPlus: IconUserPlus,
  userCircle: IconUserCircle,
  id: IconId,
  key: IconKey,
  lock: IconLock,
  lockOpen: IconLockOpen,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  shieldLock: IconShieldLock,
  bell: IconBell,
  book: IconBook,
  bookmark: IconBookmark,
  calculator: IconCalculator,
  camera: IconCamera,
  certificate: IconCertificate,
  checks: IconChecks,
  file: IconFile,
  spreadsheet: IconFileSpreadsheet,
  filter: IconFilter,
  flag: IconFlag,
  gauge: IconGauge,
  gift: IconGift,
  globe: IconGlobe,
  hash: IconHash,
  heart: IconHeart,
  inbox: IconInbox,
  info: IconInfoCircle,
  layout: IconLayout,
  link: IconLink,
  list: IconList,
  listCheck: IconListCheck,
  map: IconMap,
  mapPin: IconMapPin,
  messages: IconMessages,
  moneybag: IconMoneybag,
  news: IconNews,
  notebook: IconNotebook,
  photo: IconPhoto,
  pill: IconPill,
  plug: IconPlug,
  robot: IconRobot,
  rocket: IconRocket,
  scale: IconScale,
  scan: IconScan,
  share: IconShare,
  star: IconStar,
  table: IconTable,
  tag: IconTag,
  target: IconTarget,
  testPipe: IconTestPipe,
  timeline: IconTimeline,
  tool: IconTool,
  trendUp: IconTrendingUp,
  trendDown: IconTrendingDown,
  upload: IconUpload,
  video: IconVideo,
  vaccine: IconVaccine,
  gavel: IconGavel,
  handStop: IconHandStop,
}

/** 根节点图标解析（模块树/权限矩阵共用）：配置覆盖 → 名称关键字 → 内置根映射 → folder。 */
const ROOT_ICON_OVERRIDES: Record<number, string> = {
  11: 'base', 12: 'product', 13: 'inventory', 14: 'sales', 15: 'production', 16: 'procurement',
  17: 'finance', 18: 'hr', 19: 'vehicle', 20: 'barcode', 21: 'workflow', 22: 'report', 23: 'settings',
  24: 'sample', 25: 'query', 26: 'product', 27: 'production', 28: 'outsource', 29: 'equipment',
  30: 'customs', 32: 'finance', 33: 'quality', 38: 'hr', 39: 'quality',
}

const ROOT_ICON_KEYWORDS: [string, string][] = [
  ['采购', 'procurement'], ['销售', 'sales'], ['生产', 'production'], ['BOM', 'production'],
  ['制造', 'production'], ['工艺', 'production'], ['制程', 'production'], ['工序', 'production'],
  ['半成品', 'product'], ['产品', 'product'], ['人事', 'hr'], ['人力资源', 'hr'], ['考勤', 'hr'],
  ['工资', 'hr'], ['薪资', 'hr'], ['招聘', 'hr'], ['财务', 'finance'], ['应收', 'finance'],
  ['应付', 'finance'], ['会计', 'finance'], ['海关', 'customs'], ['报关', 'customs'],
  ['质量', 'quality'], ['质检', 'quality'], ['品管', 'quality'], ['品质', 'quality'], ['品检', 'quality'],
  ['报表', 'report'], ['查询', 'query'], ['基础资料', 'base'], ['基本资料', 'base'], ['资料', 'base'],
  ['系统', 'settings'], ['设置', 'settings'], ['权限', 'settings'], ['设备', 'equipment'],
  ['机器', 'equipment'], ['模具', 'equipment'], ['车辆', 'vehicle'], ['车队', 'vehicle'],
  ['汽车', 'vehicle'], ['条码', 'barcode'], ['条形码', 'barcode'], ['工作流', 'workflow'],
  ['流程', 'workflow'], ['打样', 'sample'], ['样品', 'sample'], ['托外', 'outsource'], ['外发', 'outsource'],
  ['客户', 'customer'], ['供应商', 'supplier'], ['库存', 'inventory'], ['仓存', 'inventory'],
  ['盘点', 'inventory'], ['单据', 'document'], ['订单', 'document'],
]

export function resolveRootIcon(rootId: number, rootLabel: string): string {
  const overrideIcon = ROOT_ICON_OVERRIDES[rootId]
  if (overrideIcon) return overrideIcon
  for (const [keyword, icon] of ROOT_ICON_KEYWORDS) {
    if (rootLabel.includes(keyword)) return icon
  }
  if (rootId === 13) return 'inventory'
  if (rootId === 14) return 'sales'
  if (rootId === 15) return 'procurement'
  return 'folder'
}
