-- Intended reconfiguration of residual chooser filters (by business intent, not DSL translation).
-- Drift guard: only writes when FILTER_STRUCT is still NULL and the migration log row is not CONVERTED,
-- so a later manual edit or an earlier backfill is never overwritten.
-- Generated by: EOS.API.Tests/Tools/ChooserReconfigureTool.cs (reproducible).

SET NOCOUNT ON;

DECLARE @GUARD NVARCHAR(400) = N'本脚本只能在 EOS.ERP 数据库内执行，当前库为 ' + DB_NAME() + N'。';
IF DB_NAME() <> N'EOS.ERP' THROW 50000, @GUARD, 1;

BEGIN TRANSACTION;

CREATE TABLE #RECONF (T_ID NVARCHAR(100) NOT NULL, F_ID NVARCHAR(100) NOT NULL, SERIAL_NO INT NOT NULL, ACTIVE_TAG BIT NOT NULL, STRUCT NVARCHAR(MAX) NOT NULL);
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_BASEPAY_D', N'EMP_NO', 1, 1, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_BASEPAY_M"},{"table":"HR_BASEPAY_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_BASEPAY_M","column":"BASEPAY_TYPE"},"right":{"kind":"column","table":"HR_BASEPAY_D","column":"BASEPAY_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_BASEPAY_M","column":"BASEPAY_NO"},"right":{"kind":"column","table":"HR_BASEPAY_D","column":"BASEPAY_NO"}},
    {"field":"HR_BASEPAY_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_BASEPAY_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HRM_BASEPAY_D', N'EMP_NO', 1, 1, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_BASEPAY_M"},{"table":"HR_BASEPAY_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_BASEPAY_M","column":"BASEPAY_TYPE"},"right":{"kind":"column","table":"HR_BASEPAY_D","column":"BASEPAY_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_BASEPAY_M","column":"BASEPAY_NO"},"right":{"kind":"column","table":"HR_BASEPAY_D","column":"BASEPAY_NO"}},
    {"field":"HR_BASEPAY_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_BASEPAY_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_WAGE_D', N'EMP_NO', 1, 1, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_WAGE_D', N'EMP_NO', 2, 1, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_DIMISSION_M","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_WAGE_D', N'IN_DATE', 1, 0, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HRM_WAGE_D', N'EMP_NO', 1, 1, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HRM_WAGE_D', N'EMP_NO', 2, 0, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_DIMISSION_M","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HRM_WAGE_D', N'IN_DATE', 1, 0, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_SAFE_D', N'IN_DATE', 1, 0, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_SUBTRACT_D', N'IN_DATE', 1, 0, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WAGE_M"},{"table":"HR_WAGE_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_TYPE"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_M","column":"WAGE_NO"},"right":{"kind":"column","table":"HR_WAGE_D","column":"WAGE_NO"}},
    {"field":"HR_WAGE_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_WAGE_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HRM_PLAN_D', N'EMP_NO', 1, 1, N'{"logic":"AND","items":[
  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_PLAN_M"},{"table":"HR_PLAN_D"}],"filter":[
    {"operator":"EQ","left":{"kind":"column","table":"HR_PLAN_M","column":"PLAN_TYPE"},"right":{"kind":"column","table":"HR_PLAN_D","column":"PLAN_TYPE"}},
    {"operator":"EQ","left":{"kind":"column","table":"HR_PLAN_M","column":"PLAN_NO"},"right":{"kind":"column","table":"HR_PLAN_D","column":"PLAN_NO"}},
    {"field":"HR_PLAN_M.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
    {"operator":"EQ","left":{"kind":"column","table":"HR_PLAN_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}
  ]}}
]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_WAGE', N'WAGE_FIELD', 1, 1, N'{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"},{"field":"FIELDS.F_ID","operator":"LIKE","value":"%_ITEM%"},{"operator":"NOT_IN","left":{"kind":"column","table":"FIELDS","column":"F_ID"},"subquery":{"from":[{"table":"HR_WAGE"}],"column":"WAGE_FIELD"}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_WAGE', N'WAGE_FIELD_DESC', 1, 1, N'{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HRM_WAGE', N'WAGE_FIELD', 1, 1, N'{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"},{"field":"FIELDS.F_ID","operator":"LIKE","value":"%_ITEM%"},{"operator":"NOT_IN","left":{"kind":"column","table":"FIELDS","column":"F_ID"},"subquery":{"from":[{"table":"HRM_WAGE"}],"column":"WAGE_FIELD"}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HRM_WAGE', N'WAGE_FIELD_DESC', 1, 1, N'{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'SFC_PLAN_PROCESS_M', N'TIMETYPE_ID', 1, 1, N'{"logic":"OR","items":[{"field":"HR_TIMETYPE.TIMETYPE_ID","operator":"EQ","value":"白班"},{"field":"HR_TIMETYPE.TIMETYPE_ID","operator":"EQ","value":"晚班"}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'MOC_PRODUCE_M', N'ORDER_TYPE', 3, 1, N'{"logic":"AND","items":[{"field":"PUR_APPLY_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"PUR_APPLY_D.APPLY_TYPE","operator":"EQ","value":"CLQG"},{"operator":"GT","left":{"kind":"arith","op":"-","left":{"kind":"column","table":"PUR_APPLY_D","column":"QTY"},"right":{"kind":"column","table":"PUR_APPLY_D","column":"PURCHASE_QTY"}},"right":{"kind":"literal","value":"0"}},{"field":"PRODUCT.MAIN_SOURCE","operator":"EQ","value":"2"},{"operator":"IN","left":{"kind":"column","table":"PUR_APPLY_D","column":"PRO_NO"},"subquery":{"from":[{"table":"BOM_STRU_M"}],"column":"PRO_NO"}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'PUR_PURCHASE_D', N'PRO_NO', 4, 1, N'{"logic":"AND","items":[{"field":"PUR_APPLY_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"operator":"GT","left":{"kind":"column","table":"PUR_APPLY_D","column":"QTY"},"right":{"kind":"column","table":"PUR_APPLY_D","column":"PURCHASE_QTY"}},{"field":"PUR_APPLY_D.FINISHED_TAG","operator":"EQ","value":"0"},{"operator":"NOT_IN","left":{"kind":"column","table":"PUR_APPLY_D","column":"APPLY_NO"},"subquery":{"from":[{"table":"MOC_PRODUCE_M"}],"column":"ORDER_NO"}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'COP_QUOTE_D', N'CHAFFER_NO', 1, 0, N'{"logic":"AND","items":[{"field":"COP_CHAFFER_M.CLIENT_ID","operator":"EQ","value":"{m.CLIENT_ID}"},{"field":"COP_CHAFFER_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"COP_CHAFFER_D.CURR_ID","operator":"EQ","value":"{m.CURR_ID}"},{"operator":"NOT_EXISTS","subquery":{"from":[{"table":"COP_QUOTE_D"}],"filter":[{"operator":"EQ","left":{"kind":"column","table":"COP_QUOTE_D","column":"CHAFFER_TYPE"},"right":{"kind":"column","table":"COP_CHAFFER_D","column":"CHAFFER_TYPE"}},{"operator":"EQ","left":{"kind":"column","table":"COP_QUOTE_D","column":"CHAFFER_NO"},"right":{"kind":"column","table":"COP_CHAFFER_D","column":"CHAFFER_NO"}},{"operator":"EQ","left":{"kind":"column","table":"COP_QUOTE_D","column":"CHAFFER_SERIAL_NO"},"right":{"kind":"column","table":"COP_CHAFFER_D","column":"SERIAL_NO"}}]}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'MOU_ASSESS_M', N'PRO_NO', 1, 1, N'{"logic":"AND","items":[{"field":"PRODUCT.BUSINESS_TAG","operator":"EQ","value":"0"},{"field":"PRODUCT.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"PRODUCT.CLIENT_ID","operator":"EQ","value":"{m.CLIENT_ID}"},{"operator":"NOT_IN","left":{"kind":"column","table":"PRODUCT","column":"PRO_NO"},"subquery":{"from":[{"table":"MOU_ASSESS_M"}],"column":"PRO_NO","filter":[{"field":"MOU_ASSESS_M.ASSESS_NO","operator":"NE","value":"{m.ASSESS_NO}"}]}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'MOU_BATCHIN_D', N'BATCH_NO', 2, 1, N'{"logic":"AND","items":[{"field":"MOU_BATCHTOP_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"MOU_BATCHTOP_M.MOU_SORT","operator":"EQ","value":"3"},{"field":"MOU_BATCHTOP_M.CLIENT_ID","operator":"EQ","value":"{d.CLIENT_ID}"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_BATCHTOP_M","column":"BATCH_NO"},"subquery":{"from":[{"table":"MOU_BATCHIN_D"}],"column":"BATCH_NO","filter":[{"field":"MOU_BATCHIN_D.BATCHIN_NO","operator":"NE","value":"{m.BATCHIN_NO}"}]}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'MOU_BATCHIN_D', N'BATCH_NO', 3, 1, N'{"logic":"AND","items":[{"field":"MOU_BATCHTOP_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"MOU_BATCHTOP_M.MOU_SORT","operator":"EQ","value":"2"},{"field":"MOU_BATCHTOP_M.CLIENT_ID","operator":"EQ","value":"{d.CLIENT_ID}"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_BATCHTOP_M","column":"BATCH_NO"},"subquery":{"from":[{"table":"MOU_BATCHIN_D"}],"column":"BATCH_NO","filter":[{"field":"MOU_BATCHIN_D.BATCHIN_NO","operator":"NE","value":"{m.BATCHIN_NO}"}]}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'MOU_GET2_D', N'APPLY_NO', 1, 1, N'{"logic":"AND","items":[{"field":"MOU_APPLY_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_APPLY_M","column":"APPLY_NO"},"subquery":{"from":[{"table":"MOU_GET2_D"}],"column":"APPLY_NO","filter":[{"field":"MOU_GET2_D.GET_NO","operator":"NE","value":"{m.GET_NO}"}]}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'MOU_GET2_D', N'APPLY_NO', 2, 1, N'{"logic":"AND","items":[{"field":"MOU_BATCH_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_BATCH_M","column":"BATCH_NO"},"subquery":{"from":[{"table":"MOU_GET2_D"}],"column":"APPLY_NO","filter":[{"field":"MOU_GET2_D.GET_NO","operator":"NE","value":"{m.GET_NO}"}]}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'HR_WORKTIME_D', N'EMP_NO', 1, 1, N'{"logic":"AND","items":[{"field":"HR_EMPLOYEE.IN_DATE","operator":"LE","value":"{m.COUNT_DATE}"},{"group":{"logic":"OR","items":[{"field":"HR_EMPLOYEE.DIMISSION_DATE","operator":"IS_NULL"},{"field":"HR_EMPLOYEE.DIMISSION_DATE","operator":"GT","value":"{m.COUNT_DATE}"}]}},{"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},{"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WORKTIME_D"},{"table":"HR_WORKTIME_M"}],"filter":[{"field":"HR_WORKTIME_M.COUNT_DATE","operator":"EQ","value":"{m.COUNT_DATE}"},{"operator":"EQ","left":{"kind":"column","table":"HR_WORKTIME_M","column":"WORKTIME_TYPE"},"right":{"kind":"column","table":"HR_WORKTIME_D","column":"WORKTIME_TYPE"}},{"operator":"EQ","left":{"kind":"column","table":"HR_WORKTIME_M","column":"WORKTIME_NO"},"right":{"kind":"column","table":"HR_WORKTIME_D","column":"WORKTIME_NO"}},{"operator":"EQ","left":{"kind":"column","table":"HR_WORKTIME_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}]}}]}');
INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'SFC_PLAN_D', N'PRO_NO', 2, 0, N'{"logic":"AND","items":[{"field":"COP_SHIPMENT_D.CLIENT_ID","operator":"EQ","value":"{d.CLIENT_ID}"},{"field":"COP_SHIPMENT_D.FINISHED_TAG","operator":"EQ","value":"0"},{"operator":"NOT_EXISTS","subquery":{"from":[{"table":"SFC_PLAN_M"},{"table":"SFC_PLAN_D"}],"filter":[{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_M","column":"PLAN_TYPE"},"right":{"kind":"column","table":"SFC_PLAN_D","column":"PLAN_TYPE"}},{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_M","column":"PLAN_NO"},"right":{"kind":"column","table":"SFC_PLAN_D","column":"PLAN_NO"}},{"field":"SFC_PLAN_M.SORT_IDX","operator":"EQ","value":"{m.SORT_IDX}"},{"field":"SFC_PLAN_D.PLAN_NO","operator":"NE","value":"{m.PLAN_NO}"},{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_D","column":"SHIPMENT_NO"},"right":{"kind":"column","table":"COP_SHIPMENT_D","column":"SHIPMENT_NO"}},{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_D","column":"SHIPMENT_SERIAL_NO"},"right":{"kind":"column","table":"COP_SHIPMENT_D","column":"SERIAL_NO"}}]}}]}');

-- 1) FILTER_STRUCT 回填（键 + 待重建三态守卫：NULL 且日志未转换才落）
UPDATE c SET FILTER_STRUCT = r.STRUCT, ACTIVE_TAG = r.ACTIVE_TAG, LAST_UPDATE_BY = N'EOS-MIG', LAST_UPDATE_DATE = SYSDATETIME()
FROM dbo.FIELD_DATASOURCE c
JOIN #RECONF r ON r.T_ID = c.T_ID AND r.F_ID = c.F_ID AND r.SERIAL_NO = c.SERIAL_NO
LEFT JOIN dbo.CHOOSER_FILTER_MIGRATION_LOG l ON l.T_ID = c.T_ID AND l.F_ID = c.F_ID AND l.SERIAL_NO = c.SERIAL_NO
WHERE c.FILTER_STRUCT IS NULL
  AND (l.STATUS IS NULL OR l.STATUS <> N'CONVERTED');

-- 2) 迁移日志状态收敛（回填行）
UPDATE l SET STATUS = N'CONVERTED', ERROR = NULL
FROM dbo.CHOOSER_FILTER_MIGRATION_LOG l
JOIN #RECONF r ON r.T_ID = l.T_ID AND r.F_ID = l.F_ID AND r.SERIAL_NO = l.SERIAL_NO
WHERE l.STATUS <> N'CONVERTED';

-- 3) 过时日志收敛：SYS_WORK_TASK.W_M_IDX 数据源已有 STRUCT（早前回填），收口迁移日志状态
UPDATE l SET STATUS = N'CONVERTED', ERROR = NULL
FROM dbo.CHOOSER_FILTER_MIGRATION_LOG l
JOIN dbo.FIELD_DATASOURCE c ON c.T_ID = l.T_ID AND c.F_ID = l.F_ID AND c.SERIAL_NO = l.SERIAL_NO
WHERE l.T_ID = N'SYS_WORK_TASK' AND l.F_ID = N'W_M_IDX' AND l.SERIAL_NO = 1
  AND c.FILTER_STRUCT IS NOT NULL
  AND l.STATUS <> N'CONVERTED';

COMMIT TRANSACTION;
