<#
.SYNOPSIS
    Inventory of legacy Web Forms page buttons that are candidates for the
    user-triggered custom-button mechanism described in ADR-018.

.DESCRIPTION
    Scans ERP/**/*.aspx.cs for `protected void btn*_Click` handlers, drops the
    standard actions (save / delete / print / export / query / upload /
    navigation / sorting) and emits for each remaining handler its size, the
    stored procedures it calls, and the SQL write verbs it touches. The result
    is the raw evidence used by the ADR-018 coverage review: a judgement about
    whether a button can be carried by the closed handler set, needs its own
    handler, or belongs to another mechanism (batch job page, margin: page work).

    Read-only with respect to the repository; only the output file is written.

.EXAMPLE
    pwsh scripts/analyze-button-coverage.ps1
    pwsh scripts/analyze-button-coverage.ps1 -IncludeClients
#>
param(
    [string] $Root = 'D:\Larry\Documents\Project\EOS\ERP',
    [string] $Out = 'D:\Larry\Documents\Project\EOS\docs\plans\custom-button-coverage-raw.md',
    [switch] $IncludeClients
)

# Standard page actions are never custom-button candidates: they are either wired
# to the form tool bar or provided by the grid itself (sorting included).
$standard = 'save|save\d*|del|delete|delete\d*|print|print\d*|export|export\d*|query|query\d*|search|filter|upload|import|exportxls|backup|new|add|edit|copy|approve|unapprove|endcase|unendcase|close|open|refresh|cancel|back|first|prev|previous|next|last|goto|selectall|selectnone|clear|reset|download|help|sort\w*|view|submit|return|ok|confirm|reverse|undo|redo|restore|check\d*'

$files = Get-ChildItem -LiteralPath $Root -Recurse -File -Filter *.aspx.cs
if (-not $IncludeClients) {
    $files = $files | Where-Object { $_.FullName.Replace('\', '/') -notmatch '/CLIENT/' }
}

$rows = [System.Collections.Generic.List[object]]::new()
foreach ($f in $files) {
    $lines = Get-Content -LiteralPath $f.FullName -Encoding UTF8
    $rel = ($f.FullName.Substring($Root.Length)).TrimStart('\', '/')
    for ($i = 0; $i -lt $lines.Count; $i++) {
        $m = [regex]::Match($lines[$i], 'protected\s+(?:void|bool|int|string)\s+(btn\w+)_Click')
        if (-not $m.Success) { continue }
        $bare = $m.Groups[1].Value -replace '^btn', ''
        if ($bare -match "^($standard)$") { continue }

        # Handler body runs to the next member declaration, capped to keep pathological pages cheap.
        $body = [System.Collections.Generic.List[string]]::new()
        $j = $i + 1
        while ($j -lt $lines.Count -and ($j - $i) -lt 400 -and $lines[$j] -notmatch '^\s{4}(protected|public|private|internal|static)\s') {
            $body.Add($lines[$j])
            $j++
        }
        $text = $body -join "`n"

        $sprocs = @([regex]::Matches($text, 'Exec(?:ute)?StoredProcedure\s*\(\s*"([^"]+)"', 1) | ForEach-Object { $_.Groups[1].Value })
        $writes = @([regex]::Matches($text, '\b(insert\s+into|update\s+\w|delete\s+from|merge\s+into|truncate\s+table)\b', 1) | ForEach-Object { $_.Groups[1].Value.ToLower() })
        $hasUi = [bool]($text -match 'GridView|RowDataBind|DxGridView|Repeater|DataList')
        $rows.Add([pscustomobject]@{
            Page      = $rel.Replace('\', '/')
            Button    = $m.Groups[1].Value
            Lines     = $body.Count
            Sproc     = ($sprocs | Select-Object -Unique) -join ' ; '
            WriteOps  = $writes.Count
            Verbs     = (($writes | Select-Object -Unique) -join ',')
            TouchesUi = $hasUi
        })
    }
}

$rows = @($rows | Sort-Object Page, Button)
$dir = Split-Path -Parent $Out
if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# Custom-button coverage: raw evidence (generated)')
[void]$sb.AppendLine()
# 状态头带生成日期：本文件是活跃文档，无日期的生成物在文档陈旧检查里只能靠人工判断新旧。
[void]$sb.AppendLine(('> 状态：原始证据快照（生成日期 {0}）。' -f (Get-Date -Format 'yyyy-MM-dd')))
[void]$sb.AppendLine('> Generated by `pwsh scripts/analyze-button-coverage.ps1`. Do not hand-edit;')
[void]$sb.AppendLine('> regenerate when the judgement needs refreshing. Handler body is capped at 400 lines.')
[void]$sb.AppendLine('> `WriteOps` counts SQL write verbs inside the handler body (string-built SQL included);')
[void]$sb.AppendLine('> read operations (SELECT / dropdown fill / validation-only handlers) show 0 and are judged')
[void]$sb.AppendLine('> as non-mutating candidates.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Page | Button | Body lines | Write ops | Verbs | Stored procedures | Touches grid |')
[void]$sb.AppendLine('|---|---|---:|---:|---|---|---|')
foreach ($r in $rows) {
    $sproc = if ($r.Sproc) { $r.Sproc } else { '-' }
    $verbs = if ($r.Verbs) { $r.Verbs } else { '-' }
    [void]$sb.AppendLine(('| `{0}` | {1} | {2} | {3} | {4} | {5} | {6} |' -f $r.Page, $r.Button, $r.Lines, $r.WriteOps, $verbs, $sproc, $r.TouchesUi))
}
[void]$sb.AppendLine()
[void]$sb.AppendLine(('Handlers inventoried: {0} across {1} pages.' -f $rows.Count, @($rows | ForEach-Object Page | Select-Object -Unique).Count))

Set-Content -LiteralPath $Out -Value $sb.ToString() -Encoding utf8
Write-Host ("rows={0} pages={1} out={2}" -f $rows.Count, @($rows | ForEach-Object Page | Select-Object -Unique).Count, $Out)
