using System.Data;
using System.Text;
using EOS.API.Data;
using Microsoft.Data.SqlClient;
using Xunit;

namespace EOS.API.Tests.Tools;

/// <summary>
/// 按意图重配字段选择器残余行（CHOOSER_FILTER_MIGRATION_LOG 未收敛）的校验工具。
/// 读内置草案（每组一条/同构多行），逐条跑 ChooserFilterValidator.ValidateAsync
/// （QUERY_RELATION 目录 + 物理列类型 + 编译 smoke），输出 PASS/FAIL 到
/// logs/fields-chooser-reconfigure/validation.csv。
/// 运行（仓库根，须已设 EOS_ERP_TEST_CONNECTION）：
///   dotnet test EOS.API.Tests\EOS.API.Tests.csproj --filter ChooserReconfigureTool
///   并设环境变量 EOS_TOOL_RECONFIGURE=1；EOS_TOOL_RECONFIGURE_GEN=1 时生成迁移 040。
/// 迁移通道已关闭（CHOOSER_FILTER_MIGRATION_LOG 已于迁移 041 删除）；本工具仅配置校验/审计参考。
/// </summary>
[Trait("Category", "Tool")]
public sealed class ChooserReconfigureTool
{
    private static readonly Lazy<string?> ConnectionString = new(ResolveConnectionString);

    private sealed record Draft(
        string TId, string FId, int Serial, string Src, bool Active, string StructJson, string Note);

    [Fact]
    public async Task Validate_IntendedReconfigure_Drafts()
    {
        if (Environment.GetEnvironmentVariable("EOS_TOOL_RECONFIGURE") != "1")
        {
            return;
        }
        Assert.False(ConnectionString.Value is null, "拿不到开发库连接串（EOS_ERP_TEST_CONNECTION 或 ~/.codex/config.toml）");

        var drafts = BuildDrafts();
        var rows = new List<string> { "T_ID,F_ID,SERIAL_NO,SRC,ACTIVE,STATUS,ERRORS,NOTE" };
        await using var connection = new SqlConnection(ConnectionString.Value);
        await connection.OpenAsync();
        foreach (var draft in drafts)
        {
            if (!ChooserFilterStruct.TryParse(draft.StructJson, out var filter) || filter is null)
            {
                rows.Add($"{draft.TId},{draft.FId},{draft.Serial},{draft.Src},{draft.Active},PARSE_FAIL,{Escape(draft.StructJson)},{draft.Note}");
                continue;
            }
            var validation = await ChooserFilterValidator.ValidateAsync(connection, filter, draft.Src, CancellationToken.None);
            rows.Add($"{draft.TId},{draft.FId},{draft.Serial},{draft.Src},{draft.Active},{(validation.Ok ? "PASS" : "FAIL")},{Escape(string.Join(" | ", validation.Messages))},{draft.Note}");
        }

        var root = FindRepoRoot();
        var outDir = Path.Combine(root, "logs", "fields-chooser-reconfigure");
        Directory.CreateDirectory(outDir);
        await File.WriteAllTextAsync(Path.Combine(outDir, "validation.csv"), string.Join("\r\n", rows) + "\r\n", new UTF8Encoding(false));

        if (Environment.GetEnvironmentVariable("EOS_TOOL_RECONFIGURE_GEN") == "1")
        {
            await WriteMigrationAsync(connection, drafts, rows);
        }
        Assert.True(rows.Count > 1, "应至少验证一行");
    }

    private static async Task WriteMigrationAsync(SqlConnection connection, IReadOnlyList<Draft> drafts, IReadOnlyList<string> csvRows)
    {
        var pass = new List<Draft>();
        foreach (var row in csvRows.Skip(1))
        {
            var parts = row.Split(',');
            if (parts.Length >= 6 && parts[5] == "PASS")
            {
                pass.Add(drafts.First(d => d.TId == parts[0] && d.FId == parts[1] && d.Serial == int.Parse(parts[2], System.Globalization.CultureInfo.InvariantCulture)));
            }
        }
        if (pass.Count == 0)
        {
            return;
        }
        var sb = new StringBuilder();
        sb.AppendLine("-- Intended reconfiguration of residual chooser filters (by business intent, not DSL translation).");
        sb.AppendLine("-- Drift guard: only writes when FILTER_STRUCT is still NULL and the migration log row is not CONVERTED,");
        sb.AppendLine("-- so a later manual edit or an earlier backfill is never overwritten.");
        sb.AppendLine("-- Generated by: EOS.API.Tests/Tools/ChooserReconfigureTool.cs (reproducible).");
        sb.AppendLine();
        sb.AppendLine("SET NOCOUNT ON;");
        sb.AppendLine();
        sb.AppendLine("DECLARE @GUARD NVARCHAR(400) = N'本脚本只能在 EOS.ERP 数据库内执行，当前库为 ' + DB_NAME() + N'。';");
        sb.AppendLine("IF DB_NAME() <> N'EOS.ERP' THROW 50000, @GUARD, 1;");
        sb.AppendLine();
        sb.AppendLine("BEGIN TRANSACTION;");
        sb.AppendLine();
        sb.AppendLine("CREATE TABLE #RECONF (T_ID NVARCHAR(100) NOT NULL, F_ID NVARCHAR(100) NOT NULL, SERIAL_NO INT NOT NULL, ACTIVE_TAG BIT NOT NULL, STRUCT NVARCHAR(MAX) NOT NULL);");
        foreach (var d in pass)
        {
            sb.AppendLine($"INSERT INTO #RECONF (T_ID, F_ID, SERIAL_NO, ACTIVE_TAG, STRUCT) VALUES (N'{d.TId}', N'{d.FId}', {d.Serial}, {(d.Active ? 1 : 0)}, N'{d.StructJson.Replace("'", "''")}');");
        }
        sb.AppendLine();
        sb.AppendLine("-- 1) FILTER_STRUCT 回填（键 + 待重建三态守卫：NULL 且日志未转换才落）");
        sb.AppendLine("UPDATE c SET FILTER_STRUCT = r.STRUCT, ACTIVE_TAG = r.ACTIVE_TAG, LAST_UPDATE_BY = N'EOS-MIG', LAST_UPDATE_DATE = SYSDATETIME()");
        sb.AppendLine("FROM dbo.FIELD_DATASOURCE c");
        sb.AppendLine("JOIN #RECONF r ON r.T_ID = c.T_ID AND r.F_ID = c.F_ID AND r.SERIAL_NO = c.SERIAL_NO");
        sb.AppendLine("LEFT JOIN dbo.CHOOSER_FILTER_MIGRATION_LOG l ON l.T_ID = c.T_ID AND l.F_ID = c.F_ID AND l.SERIAL_NO = c.SERIAL_NO");
        sb.AppendLine("WHERE c.FILTER_STRUCT IS NULL");
        sb.AppendLine("  AND (l.STATUS IS NULL OR l.STATUS <> N'CONVERTED');");
        sb.AppendLine();
        sb.AppendLine("-- 2) 迁移日志状态收敛（回填行）");
        sb.AppendLine("UPDATE l SET STATUS = N'CONVERTED', ERROR = NULL");
        sb.AppendLine("FROM dbo.CHOOSER_FILTER_MIGRATION_LOG l");
        sb.AppendLine("JOIN #RECONF r ON r.T_ID = l.T_ID AND r.F_ID = l.F_ID AND r.SERIAL_NO = l.SERIAL_NO");
        sb.AppendLine("WHERE l.STATUS <> N'CONVERTED';");
        sb.AppendLine();
        sb.AppendLine("COMMIT TRANSACTION;");

        var path = Path.Combine(FindRepoRoot(), "EOS.API", "Data", "Migrations", "040_chooser_intent_reconfigure.sql");
        await File.WriteAllTextAsync(path, sb.ToString(), new UTF8Encoding(false));
    }

    private static IReadOnlyList<Draft> BuildDrafts()
    {
        var drafts = new List<Draft>();

        // A1: HR 工资/考勤「在职 & 未结算当月」员工排除（NOT EXISTS 多表子查询，规避 NOT IN NULL 陷阱）
        void HrExclude(string tId, string fId, int serial, string src, bool active, string m, string d, string k1, string k2, string note)
        {
            var json = """
                {"logic":"AND","items":[
                  {"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},
                  {"field":"HR_EMPLOYEE.IF_SECRECY","operator":"EQ","value":"{m.IF_SECRECY}"},
                  {"operator":"NOT_EXISTS","subquery":{"from":[{"table":"__M__"},{"table":"__D__"}],"filter":[
                    {"operator":"EQ","left":{"kind":"column","table":"__M__","column":"__K1__"},"right":{"kind":"column","table":"__D__","column":"__K1__"}},
                    {"operator":"EQ","left":{"kind":"column","table":"__M__","column":"__K2__"},"right":{"kind":"column","table":"__D__","column":"__K2__"}},
                    {"field":"__M__.COUNT_MONTH","operator":"EQ","value":"{m.COUNT_MONTH}"},
                    {"operator":"EQ","left":{"kind":"column","table":"__D__","column":"EMP_ID"},"right":{"kind":"column","table":"__SRC__","column":"EMP_ID"}}
                  ]}}
                ]}
                """
                .Replace("__M__", m)
                .Replace("__D__", d)
                .Replace("__K1__", k1)
                .Replace("__K2__", k2)
                .Replace("__SRC__", src);
            drafts.Add(new Draft(tId, fId, serial, src, active, json, note));
        }

        HrExclude("HR_BASEPAY_D", "EMP_NO", 1, "HR_EMPLOYEE", true, "HR_BASEPAY_M", "HR_BASEPAY_D", "BASEPAY_TYPE", "BASEPAY_NO", "当月未建基本工资单");
        HrExclude("HRM_BASEPAY_D", "EMP_NO", 1, "HR_EMPLOYEE", true, "HR_BASEPAY_M", "HR_BASEPAY_D", "BASEPAY_TYPE", "BASEPAY_NO", "当月未建基本工资单");
        HrExclude("HR_WAGE_D", "EMP_NO", 1, "HR_EMPLOYEE", true, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "当月未结算工资");
        HrExclude("HR_WAGE_D", "EMP_NO", 2, "HR_DIMISSION_M", true, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "离职单·当月未结算工资（主查询引用 HR_EMPLOYEE 需确认 JOIN）");
        HrExclude("HR_WAGE_D", "IN_DATE", 1, "HR_EMPLOYEE", false, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "当月未结算工资（停用）");
        HrExclude("HRM_WAGE_D", "EMP_NO", 1, "HR_EMPLOYEE", true, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "当月未结算工资");
        HrExclude("HRM_WAGE_D", "EMP_NO", 2, "HR_DIMISSION_M", false, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "离职单·当月未结算工资（停用）");
        HrExclude("HRM_WAGE_D", "IN_DATE", 1, "HR_EMPLOYEE", false, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "当月未结算工资（停用）");
        HrExclude("HR_SAFE_D", "IN_DATE", 1, "HR_EMPLOYEE", false, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "当月未结算工资（停用）");
        HrExclude("HR_SUBTRACT_D", "IN_DATE", 1, "HR_EMPLOYEE", false, "HR_WAGE_M", "HR_WAGE_D", "WAGE_TYPE", "WAGE_NO", "当月未结算工资（停用）");
        HrExclude("HRM_PLAN_D", "EMP_NO", 1, "HR_EMPLOYEE", true, "HR_PLAN_M", "HR_PLAN_D", "PLAN_TYPE", "PLAN_NO", "当月未排班");

        // A2: 工资公式字段字典选择器（FIELDS 源）
        drafts.Add(new Draft("HR_WAGE", "WAGE_FIELD", 1, "FIELDS", true,
            """{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"},{"field":"FIELDS.F_ID","operator":"LIKE","value":"%_ITEM%"},{"operator":"NOT_IN","left":{"kind":"column","table":"FIELDS","column":"F_ID"},"subquery":{"from":[{"table":"HR_WAGE"}],"column":"WAGE_FIELD"}}]}""",
            "工资项字段(HR_WAGE_D._ITEM)，排除已用"));
        drafts.Add(new Draft("HR_WAGE", "WAGE_FIELD_DESC", 1, "FIELDS", true,
            """{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"}]}""",
            "工资项描述 Companion"));
        drafts.Add(new Draft("HRM_WAGE", "WAGE_FIELD", 1, "FIELDS", true,
            """{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"},{"field":"FIELDS.F_ID","operator":"LIKE","value":"%_ITEM%"},{"operator":"NOT_IN","left":{"kind":"column","table":"FIELDS","column":"F_ID"},"subquery":{"from":[{"table":"HRM_WAGE"}],"column":"WAGE_FIELD"}}]}""",
            "工资项字段(HR_WAGE_D._ITEM)，排除已用"));
        drafts.Add(new Draft("HRM_WAGE", "WAGE_FIELD_DESC", 1, "FIELDS", true,
            """{"logic":"AND","items":[{"field":"FIELDS.T_ID","operator":"EQ","value":"HR_WAGE_D"}]}""",
            "工资项描述 Companion"));

        // A3: 班别白/晚班（IN 列表 → OR 组）
        drafts.Add(new Draft("SFC_PLAN_PROCESS_M", "TIMETYPE_ID", 1, "HR_TIMETYPE", true,
            """{"logic":"OR","items":[{"field":"HR_TIMETYPE.TIMETYPE_ID","operator":"EQ","value":"白班"},{"field":"HR_TIMETYPE.TIMETYPE_ID","operator":"EQ","value":"晚班"}]}""",
            "固定两班制"));

        // A4: 制令来源=请购
        drafts.Add(new Draft("MOC_PRODUCE_M", "ORDER_TYPE", 3, "PUR_APPLY_D", true,
            """{"logic":"AND","items":[{"field":"PUR_APPLY_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"PUR_APPLY_D.APPLY_TYPE","operator":"EQ","value":"CLQG"},{"operator":"GT","left":{"kind":"arith","op":"-","left":{"kind":"column","table":"PUR_APPLY_D","column":"QTY"},"right":{"kind":"column","table":"PUR_APPLY_D","column":"PURCHASE_QTY"}},"right":{"kind":"literal","value":"0"}},{"field":"PRODUCT.MAIN_SOURCE","operator":"EQ","value":"2"},{"operator":"IN","left":{"kind":"column","table":"PUR_APPLY_D","column":"PRO_NO"},"subquery":{"from":[{"table":"BOM_STRU_M"}],"column":"PRO_NO"}}]}""",
            "请购转制令（未采购完+主料+BOM）"));

        // A5: 采购料号=请购
        drafts.Add(new Draft("PUR_PURCHASE_D", "PRO_NO", 4, "PUR_APPLY_D", true,
            """{"logic":"AND","items":[{"field":"PUR_APPLY_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"operator":"GT","left":{"kind":"column","table":"PUR_APPLY_D","column":"QTY"},"right":{"kind":"column","table":"PUR_APPLY_D","column":"PURCHASE_QTY"}},{"field":"PUR_APPLY_D.FINISHED_TAG","operator":"EQ","value":"0"},{"operator":"NOT_IN","left":{"kind":"column","table":"PUR_APPLY_D","column":"APPLY_NO"},"subquery":{"from":[{"table":"MOC_PRODUCE_M"}],"column":"ORDER_NO"}}]}""",
            "请购转采购（未采购完，未转制令）"));

        // A6: 询价单来源=采购合同行（拼接键 → 复合键 NOT EXISTS）
        drafts.Add(new Draft("COP_QUOTE_D", "CHAFFER_NO", 1, "COP_CHAFFER_D", false,
            """{"logic":"AND","items":[{"field":"COP_CHAFFER_M.CLIENT_ID","operator":"EQ","value":"{m.CLIENT_ID}"},{"field":"COP_CHAFFER_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"COP_CHAFFER_D.CURR_ID","operator":"EQ","value":"{m.CURR_ID}"},{"operator":"NOT_EXISTS","subquery":{"from":[{"table":"COP_QUOTE_D"}],"filter":[{"operator":"EQ","left":{"kind":"column","table":"COP_QUOTE_D","column":"CHAFFER_TYPE"},"right":{"kind":"column","table":"COP_CHAFFER_D","column":"CHAFFER_TYPE"}},{"operator":"EQ","left":{"kind":"column","table":"COP_QUOTE_D","column":"CHAFFER_NO"},"right":{"kind":"column","table":"COP_CHAFFER_D","column":"CHAFFER_NO"}},{"operator":"EQ","left":{"kind":"column","table":"COP_QUOTE_D","column":"CHAFFER_SERIAL_NO"},"right":{"kind":"column","table":"COP_CHAFFER_D","column":"SERIAL_NO"}}]}}]}""",
            "合同行尚未生成询价单（停用）"));

        // A7: EXEMPTED 单据类
        drafts.Add(new Draft("MOU_ASSESS_M", "PRO_NO", 1, "PRODUCT", true,
            """{"logic":"AND","items":[{"field":"PRODUCT.BUSINESS_TAG","operator":"EQ","value":"0"},{"field":"PRODUCT.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"PRODUCT.CLIENT_ID","operator":"EQ","value":"{m.CLIENT_ID}"},{"operator":"NOT_IN","left":{"kind":"column","table":"PRODUCT","column":"PRO_NO"},"subquery":{"from":[{"table":"MOU_ASSESS_M"}],"column":"PRO_NO","filter":[{"field":"MOU_ASSESS_M.ASSESS_NO","operator":"NE","value":"{m.ASSESS_NO}"}]}}]}""",
            "品号未被其它评审单评过"));
        drafts.Add(new Draft("MOU_BATCHIN_D", "BATCH_NO", 2, "MOU_BATCHTOP_M", true,
            """{"logic":"AND","items":[{"field":"MOU_BATCHTOP_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"MOU_BATCHTOP_M.MOU_SORT","operator":"EQ","value":"3"},{"field":"MOU_BATCHTOP_M.CLIENT_ID","operator":"EQ","value":"{d.CLIENT_ID}"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_BATCHTOP_M","column":"BATCH_NO"},"subquery":{"from":[{"table":"MOU_BATCHIN_D"}],"column":"BATCH_NO","filter":[{"field":"MOU_BATCHIN_D.BATCHIN_NO","operator":"NE","value":"{m.BATCHIN_NO}"}]}}]}""",
            "量产单(SORT=3)批次号未在本单使用"));
        drafts.Add(new Draft("MOU_BATCHIN_D", "BATCH_NO", 3, "MOU_BATCHTOP_M", true,
            """{"logic":"AND","items":[{"field":"MOU_BATCHTOP_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"field":"MOU_BATCHTOP_M.MOU_SORT","operator":"EQ","value":"2"},{"field":"MOU_BATCHTOP_M.CLIENT_ID","operator":"EQ","value":"{d.CLIENT_ID}"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_BATCHTOP_M","column":"BATCH_NO"},"subquery":{"from":[{"table":"MOU_BATCHIN_D"}],"column":"BATCH_NO","filter":[{"field":"MOU_BATCHIN_D.BATCHIN_NO","operator":"NE","value":"{m.BATCHIN_NO}"}]}}]}""",
            "量产单(SORT=2)批次号未在本单使用"));
        drafts.Add(new Draft("MOU_GET2_D", "APPLY_NO", 1, "MOU_APPLY_M", true,
            """{"logic":"AND","items":[{"field":"MOU_APPLY_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_APPLY_M","column":"APPLY_NO"},"subquery":{"from":[{"table":"MOU_GET2_D"}],"column":"APPLY_NO","filter":[{"field":"MOU_GET2_D.GET_NO","operator":"NE","value":"{m.GET_NO}"}]}}]}""",
            "申请单未被本单使用（GET_NO 模板按 {m.GET_NO} 修复）"));
        drafts.Add(new Draft("MOU_GET2_D", "APPLY_NO", 2, "MOU_BATCH_M", true,
            """{"logic":"AND","items":[{"field":"MOU_BATCH_M.CONFIRM_TAG","operator":"EQ","value":"1"},{"operator":"NOT_IN","left":{"kind":"column","table":"MOU_BATCH_M","column":"BATCH_NO"},"subquery":{"from":[{"table":"MOU_GET2_D"}],"column":"APPLY_NO","filter":[{"field":"MOU_GET2_D.GET_NO","operator":"NE","value":"{m.GET_NO}"}]}}]}""",
            "申请单未被本单使用（GET_NO 模板按 {m.GET_NO} 修复）"));
        drafts.Add(new Draft("HR_WORKTIME_D", "EMP_NO", 1, "HR_EMPLOYEE", true,
            """{"logic":"AND","items":[{"field":"HR_EMPLOYEE.IN_DATE","operator":"LE","value":"{m.COUNT_DATE}"},{"group":{"logic":"OR","items":[{"field":"HR_EMPLOYEE.DIMISSION_DATE","operator":"IS_NULL"},{"field":"HR_EMPLOYEE.DIMISSION_DATE","operator":"GT","value":"{m.COUNT_DATE}"}]}},{"field":"HR_EMPLOYEE.STATE","operator":"LT","value":"4"},{"operator":"NOT_EXISTS","subquery":{"from":[{"table":"HR_WORKTIME_D"},{"table":"HR_WORKTIME_M"}],"filter":[{"field":"HR_WORKTIME_M.COUNT_DATE","operator":"EQ","value":"{m.COUNT_DATE}"},{"operator":"EQ","left":{"kind":"column","table":"HR_WORKTIME_M","column":"WORKTIME_TYPE"},"right":{"kind":"column","table":"HR_WORKTIME_D","column":"WORKTIME_TYPE"}},{"operator":"EQ","left":{"kind":"column","table":"HR_WORKTIME_M","column":"WORKTIME_NO"},"right":{"kind":"column","table":"HR_WORKTIME_D","column":"WORKTIME_NO"}},{"operator":"EQ","left":{"kind":"column","table":"HR_WORKTIME_D","column":"EMP_ID"},"right":{"kind":"column","table":"HR_EMPLOYEE","column":"EMP_ID"}}]}}]}""",
            "当月在职且未录过工时（嵌套 EXISTS 拍平为多表子查询）"));
        drafts.Add(new Draft("SFC_PLAN_D", "PRO_NO", 2, "COP_SHIPMENT_D", false,
            """{"logic":"AND","items":[{"field":"COP_SHIPMENT_D.CLIENT_ID","operator":"EQ","value":"{d.CLIENT_ID}"},{"field":"COP_SHIPMENT_D.FINISHED_TAG","operator":"EQ","value":"0"},{"operator":"NOT_EXISTS","subquery":{"from":[{"table":"SFC_PLAN_M"},{"table":"SFC_PLAN_D"}],"filter":[{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_M","column":"PLAN_TYPE"},"right":{"kind":"column","table":"SFC_PLAN_D","column":"PLAN_TYPE"}},{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_M","column":"PLAN_NO"},"right":{"kind":"column","table":"SFC_PLAN_D","column":"PLAN_NO"}},{"field":"SFC_PLAN_M.SORT_IDX","operator":"EQ","value":"{m.SORT_IDX}"},{"field":"SFC_PLAN_D.PLAN_NO","operator":"NE","value":"{m.PLAN_NO}"},{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_D","column":"SHIPMENT_NO"},"right":{"kind":"column","table":"COP_SHIPMENT_D","column":"SHIPMENT_NO"}},{"operator":"EQ","left":{"kind":"column","table":"SFC_PLAN_D","column":"SHIPMENT_SERIAL_NO"},"right":{"kind":"column","table":"COP_SHIPMENT_D","column":"SERIAL_NO"}}]}}]}""",
            "出货行未排入计划（停用；拼接键→复合键 NOT EXISTS）"));

        return drafts;
    }

    private static string Escape(string value) => value.Replace("\"", "\"\"");

    private static string FindRepoRoot()
    {
        // 优先用 csproj 注入的 RepoRoot（构建期绝对路径，与运行目录无关）
        var metadata = typeof(ChooserReconfigureTool).Assembly
            .GetCustomAttributes(typeof(System.Reflection.AssemblyMetadataAttribute), false)
            .Cast<System.Reflection.AssemblyMetadataAttribute>()
            .FirstOrDefault(attr => attr.Key == "RepoRoot");
        if (metadata is { Value.Length: > 0 } && Directory.Exists(metadata.Value))
        {
            return Path.GetFullPath(metadata.Value);
        }
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "EOS.slnx")))
        {
            dir = dir.Parent;
        }
        return dir?.FullName ?? Directory.GetCurrentDirectory();
    }

    private static string? ResolveConnectionString()
    {
        var env = Environment.GetEnvironmentVariable("EOS_ERP_TEST_CONNECTION");
        if (!string.IsNullOrWhiteSpace(env))
        {
            return env;
        }
        try
        {
            var path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".codex", "config.toml");
            var text = File.ReadAllText(path);
            var match = System.Text.RegularExpressions.Regex.Match(text, "\\[mcp_servers\\.mssql\\.env\\][\\s\\S]*?MSSQL_CONNECTION_STRING\\s*=\\s*\"([^\"]+)\"");
            return match.Success && match.Groups[1].Value.Contains("Database=EOS.ERP") ? match.Groups[1].Value : null;
        }
        catch
        {
            return null;
        }
    }
}
